const countries = [
  'Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina', 'Australia', 'Austria', 'Azerbaijan',
  'Bangladesh', 'Belarus', 'Belgium', 'Benin', 'Bolivia', 'Brazil', 'Burkina Faso', 'Burundi',
  'Cambodia', 'Cameroon', 'Canada', 'Chad', 'Chile', 'China', 'Colombia', 'Democratic Republic of the (DR Congo)', 'Cuba', 'Czech Republic (Czechia)', 'Côte d\'Ivoire (Ivory Coast)',
  'Dominican Republic',
  'Ecuador', 'Egypt', 'Ethiopia',
  'France',
  'Germany', 'Ghana', 'Greece', 'Guatemala', 'Guinea',
  'Haiti', 'Honduras', 'Hungary',
  'India', 'Indonesia', 'Iran', 'Iraq', 'Israel', 'Italy',
  'Japan', 'Jordan',
  'Kazakhstan', 'Kenya',
  'Madagascar', 'Malawi', 'Malaysia', 'Mali', 'Mexico', 'Mozambique', 'Myanmar (Burma)',
  'Nepal', 'Netherlands', 'Niger', 'Nigeria', 'North Korea',
  'Pakistan', 'Papua New Guinea', 'Peru', 'Philippines', 'Poland', 'Portugal',
  'Romania', 'Russia', 'Rwanda',
  'Saudi Arabia', 'Senegal', 'South Africa', 'South Korea', 'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Syria',
  'Taiwan', 'Tanzania', 'Thailand', 'Tunisia', 'Turkey',
  'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States', 'Uzbekistan',
  'Venezuela', 'Vietnam',
  'Yemen',
  'Zambia', 'Zimbabwe'
];

const flags = [
  '🇦🇫', '🇦🇱', '🇩🇿', '🇦🇴', '🇦🇷', '🇦🇺', '🇦🇹', '🇦🇿',
  '🇧🇩', '🇧🇾', '🇧🇪', '🇧🇯', '🇧🇴', '🇧🇷', '🇧🇫', '🇧🇮',
  '🇰🇭', '🇨🇲', '🇨🇦', '🇹🇩', '🇨🇱', '🇨🇳', '🇨🇴', '🇨🇩', '🇨🇺', '🇨🇿', '🇨🇮',
  '🇩🇴',
  '🇪🇨', '🇪🇬', '🇪🇹',
  '🇫🇷',
  '🇩🇪', '🇬🇭', '🇬🇷', '🇬🇹', '🇬🇳',
  '🇭🇹', '🇭🇳', '🇭🇺',
  '🇮🇳', '🇮🇩', '🇮🇷', '🇮🇶', '🇮🇱', '🇮🇹',
  '🇯🇵', '🇯🇴',
  '🇰🇿', '🇰🇪',
  '🇲🇬', '🇲🇼', '🇲🇾', '🇲🇱', '🇲🇽', '🇲🇿', '🇲🇲',
  '🇳🇵', '🇳🇱', '🇳🇪', '🇳🇬', '🇰🇵',
  '🇵🇰', '🇵🇬', '🇵🇪', '🇵🇭', '🇵🇱', '🇵🇹',
  '🇷🇴', '🇷🇺', '🇷🇼',
  '🇸🇦', '🇸🇳', '🇿🇦', '🇰🇷', '🇸🇸', '🇪🇸', '🇱🇰', '🇸🇩', '🇸🇾',
  '🇹🇼', '🇹🇿', '🇹🇭', '🇹🇳', '🇹🇷',
  '🇺🇬', '🇺🇦', '🇦🇪', '🇬🇧', '🇺🇸', '🇺🇿',
  '🇻🇪', '🇻🇳',
  '🇾🇪',
  '🇿🇲', '🇿🇼'
];

const languages = [
  'Arabic', 'Azerbaijani',
  'Bengali', 'Bhojpuri', 'Burmese',
  'Dutch',
  'English',
  'Filipino (Tagalog)', 'French', 'Fula',
  'German', 'Gujarati',
  'Hakka Chinese', 'Hausa', 'Hebrew', 'Hindi',
  'Igbo', 'Indonesian', 'Iranian Persian', 'Italian',
  'Javanese', 'Jin Chinese', 'Japanese',
  'Kannada', 'Korean',
  'Maithili', 'Mandarin Chinese', 'Marathi', 'Min Nan Chinese',
  'Oriya (Odia)',
  'Punjabi', 'Portuguese',
  'Romanian', 'Russian',
  'Sindhi', 'Spanish', 'Standard Arabic', 'Sunda', 'Swahili',
  'Tamil', 'Telugu', 'Thai', 'Turkish',
  'Ukrainian', 'Urdu',
  'Vietnamese',
  'Wu Chinese',
  'Yue Chinese'
];