// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxpX2CG4D5wdabY4HTBcjE72bt_l5Kb54',
    appId: '1:624426974924:web:88cf863f90c06ab65ccc69',
    messagingSenderId: '624426974924',
    projectId: 'atrove-app',
    authDomain: 'atrove-app.firebaseapp.com',
    storageBucket: 'atrove-app.appspot.com',
    measurementId: 'G-N9D7LJ5RKR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB51XDGcRaWCFecbB6LKBKdwgyxqgJRa2A',
    appId: '1:624426974924:android:9b278e566ba523ea5ccc69',
    messagingSenderId: '624426974924',
    projectId: 'atrove-app',
    storageBucket: 'atrove-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTFNf5K5ul79enOt1_EUNk2AW_puLQm2o',
    appId: '1:624426974924:ios:032bd67eb55433375ccc69',
    messagingSenderId: '624426974924',
    projectId: 'atrove-app',
    storageBucket: 'atrove-app.appspot.com',
    iosBundleId: 'com.example.closetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTFNf5K5ul79enOt1_EUNk2AW_puLQm2o',
    appId: '1:624426974924:ios:d5108fce40ef8fd95ccc69',
    messagingSenderId: '624426974924',
    projectId: 'atrove-app',
    storageBucket: 'atrove-app.appspot.com',
    iosBundleId: 'com.example.closetApp.RunnerTests',
  );
}
